Use sampleemployee;

-- 1) Insert data into thte employee table


INSERT INTO employee (EmployeeID,EmployeeFName,EmployeeLName,EmployeeAddress,EmployeeSalary,EmployeeDepartment) VALUES (101,"Michael","Stanton","5648 Non Road",72924,"Tellus Eu Augue Limited");
INSERT INTO employee (EmployeeID,EmployeeFName,EmployeeLName,EmployeeAddress,EmployeeSalary,EmployeeDepartment) VALUES (102,"Robert","Craft","Ap #866-8750 Mus. Rd.",84591,"Ut Foundation");
INSERT INTO employee (EmployeeID,EmployeeFName,EmployeeLName,EmployeeAddress,EmployeeSalary,EmployeeDepartment) VALUES (103,"Tanner","Bentley","Ap #493-5163 Accumsan Av.",67398,"Tellus Imperdiet Non LLP");
INSERT INTO employee (EmployeeID,EmployeeFName,EmployeeLName,EmployeeAddress,EmployeeSalary,EmployeeDepartment) VALUES (104,"Fulton","Hopkins","250-6977 Eleifend Rd.",65683,"Sem Semper Erat Institute");
INSERT INTO employee (EmployeeID,EmployeeFName,EmployeeLName,EmployeeAddress,EmployeeSalary,EmployeeDepartment) VALUES (105,"Hiram","Castaneda","P.O. Box 326, 7443 Tincidunt Road",71485,"Tellus Sem Mollis Institute");
INSERT INTO employee (EmployeeID,EmployeeFName,EmployeeLName,EmployeeAddress,EmployeeSalary,EmployeeDepartment) VALUES (106,"Jacob","Bowen","5257 Diam Street",76444,"Pede Institute");
INSERT INTO employee (EmployeeID,EmployeeFName,EmployeeLName,EmployeeAddress,EmployeeSalary,EmployeeDepartment) VALUES (107,"Yuli","Wright","598-7892 Cras Street",66025,"Nulla Integer PC");
INSERT INTO employee (EmployeeID,EmployeeFName,EmployeeLName,EmployeeAddress,EmployeeSalary,EmployeeDepartment) VALUES (108,"Yael","Bennett","Ap #150-4171 Et Road",79207,"Ridiculus LLC");
INSERT INTO employee (EmployeeID,EmployeeFName,EmployeeLName,EmployeeAddress,EmployeeSalary,EmployeeDepartment) VALUES (109,"Craig","Sandoval","343-3696 Consectetuer Rd.",84283,"Ante Dictum LLP");
INSERT INTO employee (EmployeeID,EmployeeFName,EmployeeLName,EmployeeAddress,EmployeeSalary,EmployeeDepartment) VALUES (110,"Amal","Pruitt","469-5441 Pede, Avenue",55304,"Sed Turpis Nec LLP");
INSERT INTO employee (EmployeeID,EmployeeFName,EmployeeLName,EmployeeAddress,EmployeeSalary,EmployeeDepartment) VALUES (111,"Alan","Barber","4338 Mi Road",73195,"Eu Enim Etiam Inc.");
INSERT INTO employee (EmployeeID,EmployeeFName,EmployeeLName,EmployeeAddress,EmployeeSalary,EmployeeDepartment) VALUES (112,"Elijah","Ryan","P.O. Box 664, 9593 Duis Street",58821,"Vitae Posuere Ltd");
INSERT INTO employee (EmployeeID,EmployeeFName,EmployeeLName,EmployeeAddress,EmployeeSalary,EmployeeDepartment) VALUES (113,"Amber","Ryan","Ap #712-8663 Sed Rd.",63626,"Faucibus Limited");
INSERT INTO employee (EmployeeID,EmployeeFName,EmployeeLName,EmployeeAddress,EmployeeSalary,EmployeeDepartment) VALUES (114,"Cassandra","Fischer","3979 Id Ave",80860,"Duis LLC");
INSERT INTO employee (EmployeeID,EmployeeFName,EmployeeLName,EmployeeAddress,EmployeeSalary,EmployeeDepartment) VALUES (115,"Rae","Long","320-2569 Pellentesque Rd.",52401,"Non Dui Nec PC");
INSERT INTO employee (EmployeeID,EmployeeFName,EmployeeLName,EmployeeAddress,EmployeeSalary,EmployeeDepartment) VALUES (116,"Lana","Allen","Ap #229-2760 Enim, Ave",83159,"Vitae Risus Duis Inc.");
INSERT INTO employee (EmployeeID,EmployeeFName,EmployeeLName,EmployeeAddress,EmployeeSalary,EmployeeDepartment) VALUES (117,"Georgia","Reese","264-8704 Et Rd.",73356,"Nisl Nulla Industries");
INSERT INTO employee (EmployeeID,EmployeeFName,EmployeeLName,EmployeeAddress,EmployeeSalary,EmployeeDepartment) VALUES (118,"Anthony","Bonner","P.O. Box 838, 296 Nibh. Avenue",82860,"Eleifend Vitae Corp.");
INSERT INTO employee (EmployeeID,EmployeeFName,EmployeeLName,EmployeeAddress,EmployeeSalary,EmployeeDepartment) VALUES (119,"Erich","Hartman","5547 Nec St.",63798,"Eu Euismod Ac Foundation");
INSERT INTO employee (EmployeeID,EmployeeFName,EmployeeLName,EmployeeAddress,EmployeeSalary,EmployeeDepartment) VALUES (120,"Quamar","Whitehead","5855 Aliquam Rd.",62924,"Neque Associates");
INSERT INTO employee (EmployeeID,EmployeeFName,EmployeeLName,EmployeeAddress,EmployeeSalary,EmployeeDepartment) VALUES (121,"Walker","Mclean","Ap #571-7964 Magna. Ave",74203,"Nunc Foundation");
INSERT INTO employee (EmployeeID,EmployeeFName,EmployeeLName,EmployeeAddress,EmployeeSalary,EmployeeDepartment) VALUES (122,"Hannah","Steele","727-6481 Pretium Street",62468,"Aliquam Nec Ltd");
INSERT INTO employee (EmployeeID,EmployeeFName,EmployeeLName,EmployeeAddress,EmployeeSalary,EmployeeDepartment) VALUES (123,"Olympia","Thomas","Ap #613-4792 Ac Avenue",64130,"Eu Neque Pellentesque Inc.");
INSERT INTO employee (EmployeeID,EmployeeFName,EmployeeLName,EmployeeAddress,EmployeeSalary,EmployeeDepartment) VALUES (124,"Jared","Lynn","Ap #605-7149 Molestie Street",61782,"Ut Nec PC");
INSERT INTO employee (EmployeeID,EmployeeFName,EmployeeLName,EmployeeAddress,EmployeeSalary,EmployeeDepartment) VALUES (125,"Xantha","Dudley","949-2663 Non, St.",79462,"Urna Nunc Inc.");
INSERT INTO employee (EmployeeID,EmployeeFName,EmployeeLName,EmployeeAddress,EmployeeSalary,EmployeeDepartment) VALUES (126,"Mark","Woodward","Ap #781-7599 Purus. Avenue",67753,"Volutpat Ornare Facilisis LLP");
INSERT INTO employee (EmployeeID,EmployeeFName,EmployeeLName,EmployeeAddress,EmployeeSalary,EmployeeDepartment) VALUES (127,"Kay","Fulton","P.O. Box 887, 3932 Felis, Rd.",82190,"Ante Blandit Viverra Consulting");
INSERT INTO employee (EmployeeID,EmployeeFName,EmployeeLName,EmployeeAddress,EmployeeSalary,EmployeeDepartment) VALUES (128,"Zephania","Schroeder","5612 Nec Rd.",56468,"In Felis Nulla Associates");
INSERT INTO employee (EmployeeID,EmployeeFName,EmployeeLName,EmployeeAddress,EmployeeSalary,EmployeeDepartment) VALUES (129,"Cassandra","Farley","866-1333 Quis, Rd.",79286,"Egestas Urna Associates");
INSERT INTO employee (EmployeeID,EmployeeFName,EmployeeLName,EmployeeAddress,EmployeeSalary,EmployeeDepartment) VALUES (130,"Eagan","Sexton","3927 Urna, St.",61860,"Turpis LLC");
INSERT INTO employee (EmployeeID,EmployeeFName,EmployeeLName,EmployeeAddress,EmployeeSalary,EmployeeDepartment) VALUES (131,"Shelly","Mcbride","P.O. Box 176, 7913 Mauris, Av.",66601,"Magnis Dis LLC");
INSERT INTO employee (EmployeeID,EmployeeFName,EmployeeLName,EmployeeAddress,EmployeeSalary,EmployeeDepartment) VALUES (132,"Germane","Carney","P.O. Box 273, 6505 Sodales Ave",66498,"Phasellus Limited");
INSERT INTO employee (EmployeeID,EmployeeFName,EmployeeLName,EmployeeAddress,EmployeeSalary,EmployeeDepartment) VALUES (133,"Beck","Rutledge","367-262 Aliquam Road",61020,"Ipsum Ac Mi PC");
INSERT INTO employee (EmployeeID,EmployeeFName,EmployeeLName,EmployeeAddress,EmployeeSalary,EmployeeDepartment) VALUES (134,"Skyler","Nolan","2643 Lorem Av.",70180,"In Tempus Eu Incorporated");
INSERT INTO employee (EmployeeID,EmployeeFName,EmployeeLName,EmployeeAddress,EmployeeSalary,EmployeeDepartment) VALUES (135,"Xandra","Tyler","P.O. Box 843, 2741 Lectus St.",56447,"Faucibus Morbi Vehicula Consulting");
INSERT INTO employee (EmployeeID,EmployeeFName,EmployeeLName,EmployeeAddress,EmployeeSalary,EmployeeDepartment) VALUES (136,"Neil","Montgomery","220-4468 Quis, Street",64275,"Mi Aliquam Gravida Corporation");
INSERT INTO employee (EmployeeID,EmployeeFName,EmployeeLName,EmployeeAddress,EmployeeSalary,EmployeeDepartment) VALUES (137,"Todd","Tyler","7537 Magna. Rd.",71112,"Et Pede Nunc Institute");
INSERT INTO employee (EmployeeID,EmployeeFName,EmployeeLName,EmployeeAddress,EmployeeSalary,EmployeeDepartment) VALUES (138,"Jesse","Chen","P.O. Box 757, 6674 Nullam Ave",78645,"Eget Foundation");
INSERT INTO employee (EmployeeID,EmployeeFName,EmployeeLName,EmployeeAddress,EmployeeSalary,EmployeeDepartment) VALUES (139,"Eugenia","Buckner","8532 Faucibus. Rd.",83971,"Dui Semper Et Incorporated");
INSERT INTO employee (EmployeeID,EmployeeFName,EmployeeLName,EmployeeAddress,EmployeeSalary,EmployeeDepartment) VALUES (140,"Adrienne","Johns","386-6509 Duis Av.",50976,"Velit Egestas Industries");
INSERT INTO employee (EmployeeID,EmployeeFName,EmployeeLName,EmployeeAddress,EmployeeSalary,EmployeeDepartment) VALUES (141,"Hadassah","Erickson","602-7898 Pharetra Ave",54447,"Justo Sit Amet Associates");
INSERT INTO employee (EmployeeID,EmployeeFName,EmployeeLName,EmployeeAddress,EmployeeSalary,EmployeeDepartment) VALUES (142,"Stella","Moran","Ap #299-2416 Sociis St.",69843,"Integer Urna Vivamus Incorporated");
INSERT INTO employee (EmployeeID,EmployeeFName,EmployeeLName,EmployeeAddress,EmployeeSalary,EmployeeDepartment) VALUES (143,"Veda","Rowland","398-8787 A Road",63293,"Rutrum Justo Praesent Corp.");
INSERT INTO employee (EmployeeID,EmployeeFName,EmployeeLName,EmployeeAddress,EmployeeSalary,EmployeeDepartment) VALUES (144,"Theodore","Holman","8865 Dictum Road",60431,"Libero Est LLP");
INSERT INTO employee (EmployeeID,EmployeeFName,EmployeeLName,EmployeeAddress,EmployeeSalary,EmployeeDepartment) VALUES (145,"Leo","Holmes","P.O. Box 652, 2673 Velit. Street",61261,"Arcu Vivamus Sit Ltd");
INSERT INTO employee (EmployeeID,EmployeeFName,EmployeeLName,EmployeeAddress,EmployeeSalary,EmployeeDepartment) VALUES (146,"Shay","Ellis","Ap #578-1412 Tellus. Avenue",70891,"Vestibulum Industries");
INSERT INTO employee (EmployeeID,EmployeeFName,EmployeeLName,EmployeeAddress,EmployeeSalary,EmployeeDepartment) VALUES (147,"Jane","Alston","5419 Fermentum Avenue",77055,"Cras Dolor Dolor Incorporated");
INSERT INTO employee (EmployeeID,EmployeeFName,EmployeeLName,EmployeeAddress,EmployeeSalary,EmployeeDepartment) VALUES (148,"Curran","Salas","594-4522 Nec St.",83947,"Eu Tempor Company");
INSERT INTO employee (EmployeeID,EmployeeFName,EmployeeLName,EmployeeAddress,EmployeeSalary,EmployeeDepartment) VALUES (149,"Jamalia","Compton","244-8846 Pede, St.",55613,"Aliquet Nec LLP");
INSERT INTO employee (EmployeeID,EmployeeFName,EmployeeLName,EmployeeAddress,EmployeeSalary,EmployeeDepartment) VALUES (150,"Solomon","Mcdowell","6759 Nulla. Street",84480,"Luctus Ut Pellentesque PC");
INSERT INTO employee (EmployeeID,EmployeeFName,EmployeeLName,EmployeeAddress,EmployeeSalary,EmployeeDepartment) VALUES (151,"Kirby","Little","Ap #621-676 Lorem St.",54835,"Ante Nunc LLP");
INSERT INTO employee (EmployeeID,EmployeeFName,EmployeeLName,EmployeeAddress,EmployeeSalary,EmployeeDepartment) VALUES (152,"Brent","Stuart","Ap #177-2307 Ut Rd.",82234,"Hendrerit Consectetuer Cursus Industries");
INSERT INTO employee (EmployeeID,EmployeeFName,EmployeeLName,EmployeeAddress,EmployeeSalary,EmployeeDepartment) VALUES (153,"Ryan","May","P.O. Box 212, 535 Donec Rd.",78721,"Egestas Corp.");
INSERT INTO employee (EmployeeID,EmployeeFName,EmployeeLName,EmployeeAddress,EmployeeSalary,EmployeeDepartment) VALUES (154,"Phelan","Mathews","P.O. Box 980, 6235 Non St.",69677,"Pharetra Felis Eget LLP");
INSERT INTO employee (EmployeeID,EmployeeFName,EmployeeLName,EmployeeAddress,EmployeeSalary,EmployeeDepartment) VALUES (155,"Laura","Savage","829-763 Sem Avenue",77170,"Bibendum Fermentum Incorporated");
INSERT INTO employee (EmployeeID,EmployeeFName,EmployeeLName,EmployeeAddress,EmployeeSalary,EmployeeDepartment) VALUES (156,"Zenia","Bowman","583-1861 Mi Ave",81977,"Et Pede LLP");
INSERT INTO employee (EmployeeID,EmployeeFName,EmployeeLName,EmployeeAddress,EmployeeSalary,EmployeeDepartment) VALUES (157,"Lacey","Hale","P.O. Box 419, 8574 Est, Street",71529,"Sed Eu Eros Ltd");
INSERT INTO employee (EmployeeID,EmployeeFName,EmployeeLName,EmployeeAddress,EmployeeSalary,EmployeeDepartment) VALUES (158,"Savannah","Bird","Ap #481-1187 Nunc Street",69732,"Libero Proin Mi PC");
INSERT INTO employee (EmployeeID,EmployeeFName,EmployeeLName,EmployeeAddress,EmployeeSalary,EmployeeDepartment) VALUES (159,"Isadora","Wolfe","864-719 Molestie Road",50217,"Aenean Limited");
INSERT INTO employee (EmployeeID,EmployeeFName,EmployeeLName,EmployeeAddress,EmployeeSalary,EmployeeDepartment) VALUES (160,"TaShya","Lester","1748 Dolor. Ave",64128,"Dui Corporation");
INSERT INTO employee (EmployeeID,EmployeeFName,EmployeeLName,EmployeeAddress,EmployeeSalary,EmployeeDepartment) VALUES (161,"Autumn","Pollard","959-2288 Cubilia St.",74242,"Amet Nulla Incorporated");
INSERT INTO employee (EmployeeID,EmployeeFName,EmployeeLName,EmployeeAddress,EmployeeSalary,EmployeeDepartment) VALUES (162,"Joel","Walker","469-9402 Ornare, Avenue",53561,"Eu Ligula Incorporated");
INSERT INTO employee (EmployeeID,EmployeeFName,EmployeeLName,EmployeeAddress,EmployeeSalary,EmployeeDepartment) VALUES (163,"Bevis","Everett","8058 A, Road",73579,"Et Rutrum Non LLP");
INSERT INTO employee (EmployeeID,EmployeeFName,EmployeeLName,EmployeeAddress,EmployeeSalary,EmployeeDepartment) VALUES (164,"Kareem","Summers","Ap #567-5185 Aliquam Street",55228,"At Velit Foundation");
INSERT INTO employee (EmployeeID,EmployeeFName,EmployeeLName,EmployeeAddress,EmployeeSalary,EmployeeDepartment) VALUES (165,"Jena","Banks","Ap #767-530 Integer Av.",66277,"Libero Proin Incorporated");
INSERT INTO employee (EmployeeID,EmployeeFName,EmployeeLName,EmployeeAddress,EmployeeSalary,EmployeeDepartment) VALUES (166,"Faith","Tillman","610-3359 Eget St.",73558,"Sapien Incorporated");
INSERT INTO employee (EmployeeID,EmployeeFName,EmployeeLName,EmployeeAddress,EmployeeSalary,EmployeeDepartment) VALUES (167,"Risa","Cannon","Ap #415-6105 Rhoncus. St.",65033,"Nunc Laoreet Lectus Consulting");
INSERT INTO employee (EmployeeID,EmployeeFName,EmployeeLName,EmployeeAddress,EmployeeSalary,EmployeeDepartment) VALUES (168,"Merrill","Sawyer","788-5646 Eros. Rd.",55944,"Phasellus Dolor Elit Limited");
INSERT INTO employee (EmployeeID,EmployeeFName,EmployeeLName,EmployeeAddress,EmployeeSalary,EmployeeDepartment) VALUES (169,"Sybill","Davenport","P.O. Box 622, 3226 Donec St.",76383,"Vivamus Molestie Dapibus Limited");
INSERT INTO employee (EmployeeID,EmployeeFName,EmployeeLName,EmployeeAddress,EmployeeSalary,EmployeeDepartment) VALUES (170,"Cleo","Riggs","Ap #409-1502 Justo St.",69634,"Sed Dictum Corp.");
INSERT INTO employee (EmployeeID,EmployeeFName,EmployeeLName,EmployeeAddress,EmployeeSalary,EmployeeDepartment) VALUES (171,"Alice","Hewitt","2543 Vitae St.",51906,"Sed Nec Institute");
INSERT INTO employee (EmployeeID,EmployeeFName,EmployeeLName,EmployeeAddress,EmployeeSalary,EmployeeDepartment) VALUES (172,"Price","Reeves","P.O. Box 378, 6390 Pede. Road",83916,"Lobortis Augue Consulting");
INSERT INTO employee (EmployeeID,EmployeeFName,EmployeeLName,EmployeeAddress,EmployeeSalary,EmployeeDepartment) VALUES (173,"Meredith","Sutton","652-6056 Ac Road",74879,"Molestie LLP");
INSERT INTO employee (EmployeeID,EmployeeFName,EmployeeLName,EmployeeAddress,EmployeeSalary,EmployeeDepartment) VALUES (174,"Ronan","Gross","P.O. Box 755, 8834 Felis, Av.",76677,"Proin Non Massa Corporation");
INSERT INTO employee (EmployeeID,EmployeeFName,EmployeeLName,EmployeeAddress,EmployeeSalary,EmployeeDepartment) VALUES (175,"Maxine","Rogers","475-2047 Suspendisse Av.",57637,"Metus Facilisis Corporation");
INSERT INTO employee (EmployeeID,EmployeeFName,EmployeeLName,EmployeeAddress,EmployeeSalary,EmployeeDepartment) VALUES (176,"Harlan","Acevedo","Ap #481-6313 Nibh. Av.",70605,"Curabitur Massa Incorporated");
INSERT INTO employee (EmployeeID,EmployeeFName,EmployeeLName,EmployeeAddress,EmployeeSalary,EmployeeDepartment) VALUES (177,"Daquan","Atkinson","6973 Quis, St.",82806,"Faucibus LLP");
INSERT INTO employee (EmployeeID,EmployeeFName,EmployeeLName,EmployeeAddress,EmployeeSalary,EmployeeDepartment) VALUES (178,"Dustin","Rhodes","Ap #924-7129 Ornare St.",62969,"Nonummy Ultricies Ornare Incorporated");
INSERT INTO employee (EmployeeID,EmployeeFName,EmployeeLName,EmployeeAddress,EmployeeSalary,EmployeeDepartment) VALUES (179,"Natalie","Johns","P.O. Box 950, 2368 Suspendisse Av.",50705,"Metus Vitae Velit Ltd");
INSERT INTO employee (EmployeeID,EmployeeFName,EmployeeLName,EmployeeAddress,EmployeeSalary,EmployeeDepartment) VALUES (180,"Richard","Lamb","7888 Egestas. Av.",82615,"A Limited");
INSERT INTO employee (EmployeeID,EmployeeFName,EmployeeLName,EmployeeAddress,EmployeeSalary,EmployeeDepartment) VALUES (181,"Mariam","Nixon","609-3156 Aliquam Rd.",80429,"Tellus Incorporated");
INSERT INTO employee (EmployeeID,EmployeeFName,EmployeeLName,EmployeeAddress,EmployeeSalary,EmployeeDepartment) VALUES (182,"Merrill","Alston","5760 Dolor Street",58876,"Eros Nec Tellus LLC");
INSERT INTO employee (EmployeeID,EmployeeFName,EmployeeLName,EmployeeAddress,EmployeeSalary,EmployeeDepartment) VALUES (183,"Lysandra","Donaldson","Ap #245-2901 Maecenas St.",77178,"At Lacus Institute");
INSERT INTO employee (EmployeeID,EmployeeFName,EmployeeLName,EmployeeAddress,EmployeeSalary,EmployeeDepartment) VALUES (184,"Dieter","Mcdonald","P.O. Box 609, 2900 Dolor St.",53123,"Ridiculus Mus Proin Corporation");
INSERT INTO employee (EmployeeID,EmployeeFName,EmployeeLName,EmployeeAddress,EmployeeSalary,EmployeeDepartment) VALUES (185,"Adele","Page","Ap #635-8304 Sapien. St.",61470,"Dis Parturient Institute");
INSERT INTO employee (EmployeeID,EmployeeFName,EmployeeLName,EmployeeAddress,EmployeeSalary,EmployeeDepartment) VALUES (186,"Robert","Stephens","773 Amet Street",63065,"Nam Consequat Dolor PC");
INSERT INTO employee (EmployeeID,EmployeeFName,EmployeeLName,EmployeeAddress,EmployeeSalary,EmployeeDepartment) VALUES (187,"Melinda","Shepherd","Ap #105-7596 Dapibus Ave",80099,"Nascetur LLC");
INSERT INTO employee (EmployeeID,EmployeeFName,EmployeeLName,EmployeeAddress,EmployeeSalary,EmployeeDepartment) VALUES (188,"Gary","Acevedo","Ap #855-9351 Augue. Road",63770,"Accumsan Laoreet Inc.");
INSERT INTO employee (EmployeeID,EmployeeFName,EmployeeLName,EmployeeAddress,EmployeeSalary,EmployeeDepartment) VALUES (189,"Carson","Franks","P.O. Box 145, 3492 Sit Street",52279,"Amet Incorporated");
INSERT INTO employee (EmployeeID,EmployeeFName,EmployeeLName,EmployeeAddress,EmployeeSalary,EmployeeDepartment) VALUES (190,"Lucian","Foreman","309 Dictum Avenue",62186,"Integer Limited");
INSERT INTO employee (EmployeeID,EmployeeFName,EmployeeLName,EmployeeAddress,EmployeeSalary,EmployeeDepartment) VALUES (191,"Lenore","Joyner","475-5907 Phasellus St.",74877,"Leo Cras PC");
INSERT INTO employee (EmployeeID,EmployeeFName,EmployeeLName,EmployeeAddress,EmployeeSalary,EmployeeDepartment) VALUES (192,"Ali","Mcgee","800-7500 Erat St.",69447,"Et Company");
INSERT INTO employee (EmployeeID,EmployeeFName,EmployeeLName,EmployeeAddress,EmployeeSalary,EmployeeDepartment) VALUES (193,"Jeanette","Goodman","Ap #779-253 Nascetur Road",84017,"Gravida Praesent Eu Corporation");
INSERT INTO employee (EmployeeID,EmployeeFName,EmployeeLName,EmployeeAddress,EmployeeSalary,EmployeeDepartment) VALUES (194,"Regina","Mcgowan","P.O. Box 789, 4873 Imperdiet, St.",52913,"Risus Nunc Corp.");
INSERT INTO employee (EmployeeID,EmployeeFName,EmployeeLName,EmployeeAddress,EmployeeSalary,EmployeeDepartment) VALUES (195,"Jessamine","Solomon","267-9746 Vulputate, Road",68959,"Lorem Luctus Ut LLP");
INSERT INTO employee (EmployeeID,EmployeeFName,EmployeeLName,EmployeeAddress,EmployeeSalary,EmployeeDepartment) VALUES (196,"Kareem","Buckley","P.O. Box 158, 2756 Tincidunt St.",65780,"A Nunc Inc.");
INSERT INTO employee (EmployeeID,EmployeeFName,EmployeeLName,EmployeeAddress,EmployeeSalary,EmployeeDepartment) VALUES (197,"Todd","Pope","Ap #864-4185 Nam Avenue",60259,"Nunc Sit Foundation");
INSERT INTO employee (EmployeeID,EmployeeFName,EmployeeLName,EmployeeAddress,EmployeeSalary,EmployeeDepartment) VALUES (198,"Leroy","Conrad","272-4711 Eu Av.",76861,"Id Blandit Consulting");
INSERT INTO employee (EmployeeID,EmployeeFName,EmployeeLName,EmployeeAddress,EmployeeSalary,EmployeeDepartment) VALUES (199,"Kirk","Middleton","Ap #659-5644 Tincidunt, Street",80554,"Vitae Institute");
INSERT INTO employee (EmployeeID,EmployeeFName,EmployeeLName,EmployeeAddress,EmployeeSalary,EmployeeDepartment) VALUES (200,"Graham","Pennington","Ap #610-3437 Congue, Street",75787,"Erat Corporation");
