Use sampleemployee;

-- 2) Insert into Department table
INSERT INTO department (DepartmentID,DepartmentName,DepartmentLocation) VALUES (101,"Luctus Curabitur Egestas Industries","Anambra");
INSERT INTO department (DepartmentID,DepartmentName,DepartmentLocation) VALUES (102,"Nunc Associates","C");
INSERT INTO department (DepartmentID,DepartmentName,DepartmentLocation) VALUES (103,"In Nec PC","Victoria");
INSERT INTO department (DepartmentID,DepartmentName,DepartmentLocation) VALUES (104,"Magna Duis Consulting","AQ");
INSERT INTO department (DepartmentID,DepartmentName,DepartmentLocation) VALUES (105,"Lobortis Risus In Institute","Hamburg");
INSERT INTO department (DepartmentID,DepartmentName,DepartmentLocation) VALUES (106,"Turpis Nec PC","San José");
INSERT INTO department (DepartmentID,DepartmentName,DepartmentLocation) VALUES (107,"Vel Pede Limited","NI");
INSERT INTO department (DepartmentID,DepartmentName,DepartmentLocation) VALUES (108,"Convallis Erat Eget PC","Alberta");
INSERT INTO department (DepartmentID,DepartmentName,DepartmentLocation) VALUES (109,"Erat LLP","LU");
INSERT INTO department (DepartmentID,DepartmentName,DepartmentLocation) VALUES (110,"Egestas Nunc Sed Ltd","BW");
INSERT INTO department (DepartmentID,DepartmentName,DepartmentLocation) VALUES (111,"Purus Gravida Sagittis Corp.","SIC");
INSERT INTO department (DepartmentID,DepartmentName,DepartmentLocation) VALUES (112,"Amet Risus Donec Corp.","New South Wales");
INSERT INTO department (DepartmentID,DepartmentName,DepartmentLocation) VALUES (113,"Laoreet Ipsum Curabitur Institute","Berlin");
INSERT INTO department (DepartmentID,DepartmentName,DepartmentLocation) VALUES (114,"Luctus Felis Purus Corp.","Odisha");
INSERT INTO department (DepartmentID,DepartmentName,DepartmentLocation) VALUES (115,"Pretium Aliquet Metus Ltd","RM");
INSERT INTO department (DepartmentID,DepartmentName,DepartmentLocation) VALUES (116,"A Purus Company","L");
INSERT INTO department (DepartmentID,DepartmentName,DepartmentLocation) VALUES (117,"Fringilla Cursus Purus Corp.","ON");
INSERT INTO department (DepartmentID,DepartmentName,DepartmentLocation) VALUES (118,"Et Corp.","Merionethshire");
INSERT INTO department (DepartmentID,DepartmentName,DepartmentLocation) VALUES (119,"Phasellus At Augue LLC","PB");
INSERT INTO department (DepartmentID,DepartmentName,DepartmentLocation) VALUES (120,"Dolor Institute","PB");
INSERT INTO department (DepartmentID,DepartmentName,DepartmentLocation) VALUES (121,"Tempor Incorporated","NI");
INSERT INTO department (DepartmentID,DepartmentName,DepartmentLocation) VALUES (122,"Vehicula Limited","Wie");
INSERT INTO department (DepartmentID,DepartmentName,DepartmentLocation) VALUES (123,"Nulla Ante LLP","South Island");
INSERT INTO department (DepartmentID,DepartmentName,DepartmentLocation) VALUES (124,"Nascetur Ridiculus Ltd","Canarias");
INSERT INTO department (DepartmentID,DepartmentName,DepartmentLocation) VALUES (125,"Sagittis Augue Associates","Minas Gerais");
INSERT INTO department (DepartmentID,DepartmentName,DepartmentLocation) VALUES (126,"Sed Facilisis Industries","Wie");
INSERT INTO department (DepartmentID,DepartmentName,DepartmentLocation) VALUES (127,"Ante Limited","Leinster");
INSERT INTO department (DepartmentID,DepartmentName,DepartmentLocation) VALUES (128,"Ultricies Dignissim Lacus Consulting","Vienna");
INSERT INTO department (DepartmentID,DepartmentName,DepartmentLocation) VALUES (129,"Vitae Odio Associates","Washington");
INSERT INTO department (DepartmentID,DepartmentName,DepartmentLocation) VALUES (130,"Et Eros Proin LLP","Île-de-France");
INSERT INTO department (DepartmentID,DepartmentName,DepartmentLocation) VALUES (131,"Sed Institute","Basse-Normandie");
INSERT INTO department (DepartmentID,DepartmentName,DepartmentLocation) VALUES (132,"Iaculis Enim Sit Institute","PO");
INSERT INTO department (DepartmentID,DepartmentName,DepartmentLocation) VALUES (133,"Felis Purus Ac Company","NI");
INSERT INTO department (DepartmentID,DepartmentName,DepartmentLocation) VALUES (134,"Tempor Est Ac Institute","SP");
INSERT INTO department (DepartmentID,DepartmentName,DepartmentLocation) VALUES (135,"Rutrum Lorem Ltd","Provence-Alpes-Côte d'Azur");
INSERT INTO department (DepartmentID,DepartmentName,DepartmentLocation) VALUES (136,"Ac Mattis Incorporated","Vienna");
INSERT INTO department (DepartmentID,DepartmentName,DepartmentLocation) VALUES (137,"Aenean Egestas Hendrerit Inc.","Leinster");
INSERT INTO department (DepartmentID,DepartmentName,DepartmentLocation) VALUES (138,"Magnis Dis Corporation","Pennsylvania");
INSERT INTO department (DepartmentID,DepartmentName,DepartmentLocation) VALUES (139,"Ornare Placerat Orci Corporation","SC");
INSERT INTO department (DepartmentID,DepartmentName,DepartmentLocation) VALUES (140,"Eu Erat Semper PC","CV");
INSERT INTO department (DepartmentID,DepartmentName,DepartmentLocation) VALUES (141,"Suspendisse Foundation","Şan");
INSERT INTO department (DepartmentID,DepartmentName,DepartmentLocation) VALUES (142,"Interdum Consulting","Noord Holland");
INSERT INTO department (DepartmentID,DepartmentName,DepartmentLocation) VALUES (143,"Neque Morbi Quis Incorporated","MU");
INSERT INTO department (DepartmentID,DepartmentName,DepartmentLocation) VALUES (144,"Enim Non Nisi Foundation","VII");
INSERT INTO department (DepartmentID,DepartmentName,DepartmentLocation) VALUES (145,"Faucibus LLP","SI");
INSERT INTO department (DepartmentID,DepartmentName,DepartmentLocation) VALUES (146,"Nunc Limited","Saskatchewan");
INSERT INTO department (DepartmentID,DepartmentName,DepartmentLocation) VALUES (147,"Nec Euismod PC","NSW");
INSERT INTO department (DepartmentID,DepartmentName,DepartmentLocation) VALUES (148,"Parturient Montes Nascetur Corp.","HP");
INSERT INTO department (DepartmentID,DepartmentName,DepartmentLocation) VALUES (149,"Donec Associates","CT");
INSERT INTO department (DepartmentID,DepartmentName,DepartmentLocation) VALUES (150,"Risus Nunc Ac Foundation","Vienna");
INSERT INTO department (DepartmentID,DepartmentName,DepartmentLocation) VALUES (151,"Sit Company","Diyarbakır");
INSERT INTO department (DepartmentID,DepartmentName,DepartmentLocation) VALUES (152,"Fringilla Mi LLC","Montana");
INSERT INTO department (DepartmentID,DepartmentName,DepartmentLocation) VALUES (153,"Erat Vitae Risus Consulting","Quebec");
INSERT INTO department (DepartmentID,DepartmentName,DepartmentLocation) VALUES (154,"Sagittis LLP","AK");
INSERT INTO department (DepartmentID,DepartmentName,DepartmentLocation) VALUES (155,"Dictum Eu Corp.","JH");
INSERT INTO department (DepartmentID,DepartmentName,DepartmentLocation) VALUES (156,"Mauris Ltd","Ogun");
INSERT INTO department (DepartmentID,DepartmentName,DepartmentLocation) VALUES (157,"Hendrerit Id Ante Industries","VIC");
INSERT INTO department (DepartmentID,DepartmentName,DepartmentLocation) VALUES (158,"Aliquam Associates","British Columbia");
INSERT INTO department (DepartmentID,DepartmentName,DepartmentLocation) VALUES (159,"Dictum Industries","Ada");
INSERT INTO department (DepartmentID,DepartmentName,DepartmentLocation) VALUES (160,"Odio Sagittis Semper LLP","Connecticut");
INSERT INTO department (DepartmentID,DepartmentName,DepartmentLocation) VALUES (161,"Ipsum Cursus Ltd","North Island");
INSERT INTO department (DepartmentID,DepartmentName,DepartmentLocation) VALUES (162,"Nunc Est LLC","North Island");
INSERT INTO department (DepartmentID,DepartmentName,DepartmentLocation) VALUES (163,"Tincidunt Orci PC","Overijssel");
INSERT INTO department (DepartmentID,DepartmentName,DepartmentLocation) VALUES (164,"Nam Ligula Elit Company","Wie");
INSERT INTO department (DepartmentID,DepartmentName,DepartmentLocation) VALUES (165,"Netus Institute","Manitoba");
INSERT INTO department (DepartmentID,DepartmentName,DepartmentLocation) VALUES (166,"Consectetuer LLP","SI");
INSERT INTO department (DepartmentID,DepartmentName,DepartmentLocation) VALUES (167,"Tellus Sem Corp.","Wie");
INSERT INTO department (DepartmentID,DepartmentName,DepartmentLocation) VALUES (168,"Nullam Nisl Incorporated","F");
INSERT INTO department (DepartmentID,DepartmentName,DepartmentLocation) VALUES (169,"Maecenas Ornare Egestas Corp.","Vienna");
INSERT INTO department (DepartmentID,DepartmentName,DepartmentLocation) VALUES (170,"Vitae Erat Institute","VII");
INSERT INTO department (DepartmentID,DepartmentName,DepartmentLocation) VALUES (171,"Morbi Metus Vivamus Inc.","WV");
INSERT INTO department (DepartmentID,DepartmentName,DepartmentLocation) VALUES (172,"Etiam Vestibulum LLP","Alberta");
INSERT INTO department (DepartmentID,DepartmentName,DepartmentLocation) VALUES (173,"In Sodales Elit Industries","ID");
INSERT INTO department (DepartmentID,DepartmentName,DepartmentLocation) VALUES (174,"Sed Ltd","Kano");
INSERT INTO department (DepartmentID,DepartmentName,DepartmentLocation) VALUES (175,"Vehicula Et Limited","U");
INSERT INTO department (DepartmentID,DepartmentName,DepartmentLocation) VALUES (176,"Faucibus Leo In Corp.","Colorado");
INSERT INTO department (DepartmentID,DepartmentName,DepartmentLocation) VALUES (177,"Dictum Cursus Industries","AK");
INSERT INTO department (DepartmentID,DepartmentName,DepartmentLocation) VALUES (178,"Consectetuer Mauris Industries","West Bengal");
INSERT INTO department (DepartmentID,DepartmentName,DepartmentLocation) VALUES (179,"Nunc Inc.","SP");
INSERT INTO department (DepartmentID,DepartmentName,DepartmentLocation) VALUES (180,"Suspendisse Non Leo Industries","X");
INSERT INTO department (DepartmentID,DepartmentName,DepartmentLocation) VALUES (181,"Mollis Duis PC","Noord Brabant");
INSERT INTO department (DepartmentID,DepartmentName,DepartmentLocation) VALUES (182,"Dignissim Industries","Ankara");
INSERT INTO department (DepartmentID,DepartmentName,DepartmentLocation) VALUES (183,"Est Company","Borno");
INSERT INTO department (DepartmentID,DepartmentName,DepartmentLocation) VALUES (184,"Laoreet Ipsum Foundation","PE");
INSERT INTO department (DepartmentID,DepartmentName,DepartmentLocation) VALUES (185,"Nulla Industries","AR");
INSERT INTO department (DepartmentID,DepartmentName,DepartmentLocation) VALUES (186,"Suspendisse Aliquet Industries","PA");
INSERT INTO department (DepartmentID,DepartmentName,DepartmentLocation) VALUES (187,"Cursus A Enim Corporation","São Paulo");
INSERT INTO department (DepartmentID,DepartmentName,DepartmentLocation) VALUES (188,"Viverra Maecenas Iaculis Limited","HE");
INSERT INTO department (DepartmentID,DepartmentName,DepartmentLocation) VALUES (189,"Eget LLC","L");
INSERT INTO department (DepartmentID,DepartmentName,DepartmentLocation) VALUES (190,"Sed Nulla Ante Company","Euskadi");
INSERT INTO department (DepartmentID,DepartmentName,DepartmentLocation) VALUES (191,"Ipsum Donec Sollicitudin Corp.","Heredia");
INSERT INTO department (DepartmentID,DepartmentName,DepartmentLocation) VALUES (192,"Non Dapibus Company","Rutland");
INSERT INTO department (DepartmentID,DepartmentName,DepartmentLocation) VALUES (193,"Nisi Mauris Institute","Aquitaine");
INSERT INTO department (DepartmentID,DepartmentName,DepartmentLocation) VALUES (194,"Aliquam Company","AP");
INSERT INTO department (DepartmentID,DepartmentName,DepartmentLocation) VALUES (195,"Porttitor Industries","Jönköpings län");
INSERT INTO department (DepartmentID,DepartmentName,DepartmentLocation) VALUES (196,"Dui In Sodales PC","PR");
INSERT INTO department (DepartmentID,DepartmentName,DepartmentLocation) VALUES (197,"Varius Et Euismod Associates","Banffshire");
INSERT INTO department (DepartmentID,DepartmentName,DepartmentLocation) VALUES (198,"Malesuada Fames Ac Ltd","VI");
INSERT INTO department (DepartmentID,DepartmentName,DepartmentLocation) VALUES (199,"Leo Elementum Sem Industries","LD");
INSERT INTO department (DepartmentID,DepartmentName,DepartmentLocation) VALUES (200,"Tempus Mauris Incorporated","H");